### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by AdemH994** [Niestsabes/poke-guesser#8]
Hello,

To make my input I needed to use the keyboard present on the front. 
My keyboard didn't work to write the pokemon name. Tested on Firefox and Edge.

Thank you for fixing this.

Best regards.

**Comment by Niestsabes** [comment]
Hi Adem,

The project is still in its alpha release phase, and the keyboard support has not been developed yet.

I'll implement this feature during the next release.
